# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fced80e026a427ee0386cf7572263e34ed530b09677c97d00a6157089c68b91d261953281b331320569f53872cb3ba5273819891a1fee3b35085edfe42dfaffb

test:
  secret_key_base: 4ec3c629b067b146e0f269388ab507d6d856eb0a670114644e0b69a9623803cef13fad305af0a4180b0bde714d85789c3f93528f8e3906f68420bc221deade71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
